---
title: "Exercícios-lista-1"
output: github_document
---


```{r}
library(tidyverse)
```
```{r}
df <- mpg
```


```{r}
df %>% is_tibble()
## [1] TRUE

# equivalente a: is_tibble(df)
```

```{r}
view(df)
```


```{r}
df %>% ggplot(aes(x = displ, y = hwy)) +
  geom_point()
```

```{r}
df %>% glimpse()
```

```{r}
df %>% nrow()
```

```{r}
df %>% is_tibble()
```
```{r}
df %>% ggplot(aes(x = cyl, y = hwy)) + 
  geom_point() 
```
```{r}
df %>% ggplot(aes(x = class, y = drv)) + 
  geom_point() 
```


```{r}
df %>% ggplot(aes(x = displ, y = hwy)) + 
  geom_point() + 
  facet_wrap(~ class, nrow = 2)
```
```{r}
df %>% ggplot(aes(x = displ, y = hwy)) + 
  geom_point() + 
  facet_wrap(vars(cyl,drv), nrow = 3)  
```
```{r}
library(ggplot2)
library(dplyr)
library(gapminder)

```

```{r}
df<-gapminder
# instale o pacote se necessário: install.packages(...)



# agora que você carregou o pacote, o objeto gapminder pode ser acessado. Dê uma olhada:
head(df)


```

```{r}
# quantas linhas?
df %>% nrow()
```

